"""phase 4 schema

Revision ID: 56360aa7cdc7
Revises: ae94d241e5a6
Create Date: 2026-06-16 00:40:37.946200
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56360aa7cdc7'
down_revision: Union[str, None] = 'ae94d241e5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', sa.String(length=16), nullable=False, server_default='us'))
        batch_op.add_column(sa.Column('data_retention_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('brand_company_name', sa.String(length=255), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('brand_logo_url', sa.String(length=1024), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('brand_primary_color', sa.String(length=16), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('brand_contact', sa.String(length=512), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('brand_contact')
        batch_op.drop_column('brand_primary_color')
        batch_op.drop_column('brand_logo_url')
        batch_op.drop_column('brand_company_name')
        batch_op.drop_column('data_retention_days')
        batch_op.drop_column('region')

    # ### end Alembic commands ###
