"""phase 2 schema

Revision ID: 5df0c07f2d68
Revises: 76dd31d38a63
Create Date: 2026-06-15 23:39:27.256195
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5df0c07f2d68'
down_revision: Union[str, None] = '76dd31d38a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('hashed_token', sa.String(length=255), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_tokens_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_tokens_prefix'), ['prefix'], unique=False)

    op.create_table('integrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('slack', 'teams', 'webhook', 'jira', 'servicenow', 'splunk', 'sentinel', 'pagerduty', name='integrationtype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('encrypted_secret', sa.Text(), nullable=False),
    sa.Column('last_status', sa.String(length=32), nullable=False),
    sa.Column('last_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrations_organization_id'), ['organization_id'], unique=False)

    op.create_table('rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.Column('remediation', sa.Text(), nullable=False),
    sa.Column('compliance', sa.JSON(), nullable=False),
    sa.Column('references', sa.JSON(), nullable=False),
    sa.Column('source', sa.Enum('system', 'custom', name='rulesource'), nullable=False),
    sa.Column('state', sa.Enum('draft', 'submitted', 'approved', name='rulestate'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rules_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_rules_organization_id'), ['organization_id'], unique=False)

    op.create_table('rule_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.Column('remediation', sa.Text(), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=False),
    sa.Column('edited_by', sa.String(length=36), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_versions_rule_id'), ['rule_id'], unique=False)

    op.create_table('device_credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('encrypted_password', sa.Text(), nullable=False),
    sa.Column('last_test_status', sa.String(length=32), nullable=False),
    sa.Column('last_test_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_credentials_device_id'), ['device_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_device_credentials_organization_id'), ['organization_id'], unique=False)

    op.create_table('rule_suppressions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('rule_key', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.Enum('disable', 'override_severity', name='suppressionaction'), nullable=False),
    sa.Column('value', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_suppressions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_suppressions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_suppressions_rule_key'), ['rule_key'], unique=False)

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connection_method', sa.String(length=16), nullable=False, server_default='manual'))
        batch_op.add_column(sa.Column('last_connection_status', sa.String(length=32), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('last_connection_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_connection_error', sa.String(length=512), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('last_connection_error')
        batch_op.drop_column('last_connection_at')
        batch_op.drop_column('last_connection_status')
        batch_op.drop_column('connection_method')

    with op.batch_alter_table('rule_suppressions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_suppressions_rule_key'))
        batch_op.drop_index(batch_op.f('ix_rule_suppressions_organization_id'))

    op.drop_table('rule_suppressions')
    with op.batch_alter_table('device_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_credentials_organization_id'))
        batch_op.drop_index(batch_op.f('ix_device_credentials_device_id'))

    op.drop_table('device_credentials')
    with op.batch_alter_table('rule_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_versions_rule_id'))

    op.drop_table('rule_versions')
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rules_organization_id'))
        batch_op.drop_index(batch_op.f('ix_rules_key'))

    op.drop_table('rules')
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrations_organization_id'))

    op.drop_table('integrations')
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_tokens_prefix'))
        batch_op.drop_index(batch_op.f('ix_api_tokens_organization_id'))

    op.drop_table('api_tokens')
    # ### end Alembic commands ###

    # Drop Postgres enum types created for Phase 2 columns so a re-upgrade after
    # downgrade does not fail. No-op on SQLite.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        for enum_name in ("integrationtype", "suppressionaction", "rulestate", "rulesource"):
            sa.Enum(name=enum_name).drop(bind, checkfirst=True)
