"""initial schema

Revision ID: 76dd31d38a63
Revises: 
Create Date: 2026-06-15 22:24:25.599923
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76dd31d38a63'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_msp', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.Enum('free', 'professional', 'msp', name='plantier'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.Enum('email', 'webhook', name='alertchannel'), nullable=False),
    sa.Column('target', sa.String(length=512), nullable=False),
    sa.Column('on_new_critical', sa.Boolean(), nullable=False),
    sa.Column('on_service_disabled', sa.Boolean(), nullable=False),
    sa.Column('on_firmware_vuln', sa.Boolean(), nullable=False),
    sa.Column('on_critical_drift', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_subscriptions_organization_id'), ['organization_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('before', sa.JSON(), nullable=False),
    sa.Column('after', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_organization_id'), ['organization_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'analyst', 'viewer', 'msp_operator', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=False),
    sa.Column('backup_codes', sa.JSON(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notify_new_critical', sa.Boolean(), nullable=False),
    sa.Column('notify_scan_failed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('serial', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('firmware', sa.String(length=128), nullable=False),
    sa.Column('friendly_name', sa.String(length=255), nullable=False),
    sa.Column('latest_score', sa.Float(), nullable=False),
    sa.Column('latest_grade', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_serial'), ['serial'], unique=False)

    op.create_table('drift_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('previous_analysis_id', sa.String(length=36), nullable=False),
    sa.Column('current_analysis_id', sa.String(length=36), nullable=False),
    sa.Column('alert_count', sa.Integer(), nullable=False),
    sa.Column('severity_counts', sa.JSON(), nullable=False),
    sa.Column('alerts', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drift_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drift_events_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drift_events_organization_id'), ['organization_id'], unique=False)

    op.create_table('schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('frequency', sa.Enum('manual', 'daily', 'weekly', 'monthly', name='schedulefrequency'), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('blackout_windows', sa.JSON(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedules_device_id'), ['device_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_schedules_organization_id'), ['organization_id'], unique=False)

    op.create_table('tsrs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tsrs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tsrs_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tsrs_organization_id'), ['organization_id'], unique=False)

    op.create_table('analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('tsr_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'complete', 'failed', name='analysisstatus'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=8), nullable=False),
    sa.Column('finding_count', sa.Integer(), nullable=False),
    sa.Column('critical_count', sa.Integer(), nullable=False),
    sa.Column('high_count', sa.Integer(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tsr_id'], ['tsrs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyses_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_tsr_id'), ['tsr_id'], unique=False)

    op.create_table('findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('business_impact', sa.Text(), nullable=False),
    sa.Column('technical_impact', sa.Text(), nullable=False),
    sa.Column('remediation', sa.Text(), nullable=False),
    sa.Column('verification', sa.JSON(), nullable=False),
    sa.Column('compliance', sa.JSON(), nullable=False),
    sa.Column('exploitability', sa.String(length=16), nullable=False),
    sa.Column('object_name', sa.String(length=255), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=False),
    sa.Column('object_detail', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'acknowledged', 'in_progress', 'fixed', 'false_positive', 'accepted_risk', 'suppressed', name='findingstatus'), nullable=False),
    sa.Column('assignee_id', sa.String(length=36), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ticket_ref', sa.String(length=255), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('accepted_risk_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_off_by', sa.String(length=36), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_assignee_id'), ['assignee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_status'), ['status'], unique=False)

    op.create_table('finding_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=True),
    sa.Column('author_email', sa.String(length=255), nullable=False),
    sa.Column('comment_type', sa.Enum('comment', 'status_change', 'assignment', 'attachment', name='commenttype'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=False),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('finding_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finding_comments_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_comments_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finding_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finding_comments_organization_id'))
        batch_op.drop_index(batch_op.f('ix_finding_comments_finding_id'))

    op.drop_table('finding_comments')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_status'))
        batch_op.drop_index(batch_op.f('ix_findings_severity'))
        batch_op.drop_index(batch_op.f('ix_findings_rule_id'))
        batch_op.drop_index(batch_op.f('ix_findings_organization_id'))
        batch_op.drop_index(batch_op.f('ix_findings_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_findings_device_id'))
        batch_op.drop_index(batch_op.f('ix_findings_assignee_id'))
        batch_op.drop_index(batch_op.f('ix_findings_analysis_id'))

    op.drop_table('findings')
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_tsr_id'))
        batch_op.drop_index(batch_op.f('ix_analyses_organization_id'))
        batch_op.drop_index(batch_op.f('ix_analyses_device_id'))

    op.drop_table('analyses')
    with op.batch_alter_table('tsrs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tsrs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_tsrs_device_id'))

    op.drop_table('tsrs')
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_organization_id'))
        batch_op.drop_index(batch_op.f('ix_schedules_device_id'))

    op.drop_table('schedules')
    with op.batch_alter_table('drift_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drift_events_organization_id'))
        batch_op.drop_index(batch_op.f('ix_drift_events_device_id'))

    op.drop_table('drift_events')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_serial'))
        batch_op.drop_index(batch_op.f('ix_devices_organization_id'))
        batch_op.drop_index(batch_op.f('ix_devices_customer_id'))

    op.drop_table('devices')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_organization_id'))

    op.drop_table('customers')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('alert_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_subscriptions_organization_id'))

    op.drop_table('alert_subscriptions')
    op.drop_table('organizations')
    # ### end Alembic commands ###

    # Postgres creates a named TYPE for each Enum column; drop_table leaves
    # those types behind, which would break a subsequent re-upgrade. Drop them
    # explicitly. SQLite has no such types, so this is a no-op there.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        for enum_name in (
            "commenttype", "findingstatus", "analysisstatus", "schedulefrequency",
            "role", "alertchannel", "plantier",
        ):
            sa.Enum(name=enum_name).drop(bind, checkfirst=True)
