"""phase 3 schema

Revision ID: ae94d241e5a6
Revises: 5df0c07f2d68
Create Date: 2026-06-16 00:09:08.273646
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae94d241e5a6'
down_revision: Union[str, None] = '5df0c07f2d68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psirt_refresh_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ran_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('changed', sa.Boolean(), nullable=False),
    sa.Column('advisory_count', sa.Integer(), nullable=False),
    sa.Column('added', sa.JSON(), nullable=False),
    sa.Column('updated', sa.JSON(), nullable=False),
    sa.Column('affected_devices', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('psirt_refresh_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_psirt_refresh_logs_ran_at'), ['ran_at'], unique=False)

    op.create_table('sso_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('protocol', sa.Enum('oidc', 'saml', name='ssoprotocol'), nullable=False),
    sa.Column('oidc_discovery_url', sa.String(length=512), nullable=False),
    sa.Column('oidc_client_id', sa.String(length=255), nullable=False),
    sa.Column('oidc_encrypted_client_secret', sa.Text(), nullable=False),
    sa.Column('saml_idp_entity_id', sa.String(length=512), nullable=False),
    sa.Column('saml_idp_sso_url', sa.String(length=512), nullable=False),
    sa.Column('saml_idp_x509_cert', sa.Text(), nullable=False),
    sa.Column('groups_attribute', sa.String(length=128), nullable=False),
    sa.Column('group_role_map', sa.JSON(), nullable=False),
    sa.Column('default_role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sso_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sso_configs_organization_id'), ['organization_id'], unique=True)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('business_unit', sa.String(length=255), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('contact_email', sa.String(length=255), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=False, server_default=''))

    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_system', sa.String(length=32), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('ticket_url', sa.String(length=512), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('ticket_status', sa.String(length=64), nullable=False, server_default=''))

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_status', sa.String(length=32), nullable=False, server_default='none'))
        batch_op.add_column(sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=64), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(length=64), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('trial_ends_at')
        batch_op.drop_column('subscription_status')

    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_column('ticket_status')
        batch_op.drop_column('ticket_url')
        batch_op.drop_column('ticket_system')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('contact_email')
        batch_op.drop_column('business_unit')
        batch_op.drop_column('location')

    with op.batch_alter_table('sso_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sso_configs_organization_id'))

    op.drop_table('sso_configs')
    with op.batch_alter_table('psirt_refresh_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_psirt_refresh_logs_ran_at'))

    op.drop_table('psirt_refresh_logs')
    # ### end Alembic commands ###

    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        sa.Enum(name="ssoprotocol").drop(bind, checkfirst=True)
